version: '3'
services:
  n8n:
    build: .
    ports:
      - 5678:5678
    restart: always
    environment:
      - N8N_LOG_LEVEL=debug
      - N8N_METRICS=true
      - N8N_ENCRYPTION_KEY=ASDF32-324FDG-SFHYG4-5GB52G-F1234D
